language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - develop

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: develop
