language: node_js
os:
  - linux
dist: xenial
node_js:
  - stable

cache:
  directories:
    - node_modules

branches:
  only:
    - develop

install:
  - yarn install
  - DEPLOY_ENV=GH_PAGES yarn run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  local_dir: dist
  on:
    branch: develop
